title: Pre-Bootcamp-Preparation
description: >-
  So you are about to start a Software Development Bootcamp. This self-guided
  lesson is aimed at exposing you to the tools and basics you'll need to
  maximize the value of your time during your bootcamp.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
